# Generated by Django 5.1.6 on 2025-02-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=100)),
                ('number_of_students', models.IntegerField()),
                ('patron_contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='donated_books/')),
                ('book_type', models.CharField(choices=[('curriculum', 'Curriculum'), ('storybook', 'Storybook'), ('general', 'General Reading')], max_length=100)),
                ('delivery_option', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('donor_name', models.CharField(max_length=100)),
                ('contact_details', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('delivery_option', models.CharField(max_length=100)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
    ]
