# Generated by Django 5.1.6 on 2025-02-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=100)),
                ('students_count', models.IntegerField()),
                ('patron_name', models.CharField(max_length=255)),
                ('patron_contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='BookDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_email', models.EmailField(max_length=254)),
                ('book_title', models.CharField(max_length=200)),
                ('book_type', models.CharField(choices=[('curriculum', 'Curriculum'), ('storybook', 'Storybook'), ('general', 'General Reading')], max_length=50)),
                ('delivery_option', models.CharField(max_length=200)),
                ('book_image', models.ImageField(upload_to='book_donations/')),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=255)),
                ('email_or_phone', models.CharField(max_length=100)),
                ('book_title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('education', 'Educational'), ('biography', 'Biography'), ('fantasy', 'Fantasy'), ('history', 'History'), ('mystery', 'Mystery'), ('science', 'Science')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('delivery_option', models.CharField(choices=[('drop_off', 'Drop off at location'), ('personal_pickup', 'Personal pick-up')], max_length=20)),
                ('book_image', models.ImageField(upload_to='exchange_books/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BookPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledger_name', models.CharField(max_length=100)),
                ('pledger_email', models.EmailField(max_length=254)),
                ('book_title', models.CharField(max_length=200)),
                ('book_type', models.CharField(choices=[('curriculum', 'Curriculum'), ('storybook', 'Storybook'), ('general', 'General Reading')], max_length=50)),
                ('expected_donation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_impacted', models.IntegerField()),
                ('schools_reached', models.IntegerField()),
                ('exchanges', models.IntegerField()),
                ('books_donated', models.IntegerField()),
            ],
        ),
    ]
