# Generated by Django 5.1.6 on 2025-02-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=100)),
                ('no_of_students', models.PositiveIntegerField()),
                ('patron_name', models.CharField(max_length=255)),
                ('patron_contact', models.CharField(max_length=50)),
            ],
        ),
    ]
