# Generated by Django 5.1.6 on 2025-02-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('science', 'Science'), ('history', 'History'), ('biography', 'Biography')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('donor_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('delivery_option', models.CharField(choices=[('drop_off', 'Drop Off'), ('personal_pickup', 'Personal Pickup')], max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='bookexchange',
            old_name='email_or_phone',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='bookexchange',
            old_name='book_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='bookexchange',
            old_name='date_added',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='bookexchange',
            name='book_image',
        ),
        migrations.RemoveField(
            model_name='bookexchange',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='bookexchange',
            name='delivery_option',
            field=models.CharField(choices=[('drop_off', 'Drop Off'), ('personal_pickup', 'Personal Pickup')], max_length=255),
        ),
        migrations.AlterField(
            model_name='bookexchange',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('science', 'Science'), ('history', 'History'), ('biography', 'Biography')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bookexchange',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
