# Generated by Django 5.1.6 on 2025-02-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_bookclub'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=255)),
                ('donor_email', models.EmailField(max_length=254)),
                ('book_title', models.CharField(max_length=255)),
                ('book_image', models.ImageField(upload_to='donated_books/')),
                ('book_type', models.CharField(choices=[('curriculum', 'Curriculum Books'), ('storybooks', 'Storybooks'), ('general', 'General Reading Books')], max_length=20)),
                ('delivery_option', models.CharField(choices=[('drop_off', 'Drop off at nearest school book club'), ('pickup', 'Request for pickup (if available)')], max_length=20)),
                ('date_donated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=255)),
                ('donor_email', models.EmailField(max_length=254)),
                ('pledged_books', models.TextField()),
                ('date_pledged', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
