# Generated by Django 5.1.6 on 2025-02-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_book_rename_email_or_phone_bookexchange_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookexchange',
            old_name='contact',
            new_name='contact_details',
        ),
        migrations.RemoveField(
            model_name='bookexchange',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='bookexchange',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/'),
        ),
        migrations.AlterField(
            model_name='bookexchange',
            name='delivery_option',
            field=models.CharField(choices=[('Drop-off', 'Drop-off'), ('Personal Pick-up', 'Personal Pick-up')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bookexchange',
            name='genre',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Sci-Fi', 'Sci-Fi'), ('Romance', 'Romance'), ('Mystery', 'Mystery')], max_length=50),
        ),
    ]
