# Generated by Django 5.1.6 on 2025-02-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_contact_bookexchange_contact_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_impacted', models.IntegerField(default=0)),
                ('schools_reached', models.IntegerField(default=0)),
                ('book_exchanges', models.IntegerField(default=0)),
                ('books_donated', models.IntegerField(default=0)),
            ],
        ),
    ]
