# Generated by Django 5.1.6 on 2025-02-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_impactdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactdata',
            name='book_exchanges',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='impactdata',
            name='books_donated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='impactdata',
            name='schools_reached',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='impactdata',
            name='students_impacted',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
